"use client";
import { useEffect, useMemo, useState } from "react";
import { stations } from "@/lib/mock-data";

type Channel={id:string;name:string;type:"group"|"direct"|"station";members:string[];unread:number;station:string};
type Message={id:string;channelId:string;sender:string;text:string;time:string};
type TeamMember={id:string;name:string;role:string;initials:string;scope:string};
const seedChannels:Channel[]=[
 {id:"music",name:"Muziekredactie",type:"group",members:["Jasper","Tibo","Sarah"],unread:2,station:"versuz"},
 {id:"tech",name:"Techniek",type:"group",members:["Jasper","Techniek"],unread:1,station:"all"},
 {id:"team",name:"Versuz Team",type:"station",members:["Jasper","Tibo","Bram","Wouter","Sarah"],unread:0,station:"versuz"},
 {id:"tibo",name:"Tibo",type:"direct",members:["Jasper","Tibo"],unread:0,station:"versuz"}];
const seedMessages:Message[]=[
 {id:"m1",channelId:"music",sender:"Tibo",text:"Ik heb 6 nieuwe tracks klaargezet voor de meeting.",time:"08:21"},
 {id:"m2",channelId:"music",sender:"Sarah",text:"Ik luister de nieuwe Bebe Rexha straks nog na.",time:"08:24"},
 {id:"m3",channelId:"tech",sender:"Techniek",text:"De back-up encoder is opnieuw bereikbaar.",time:"07:58"},
 {id:"m4",channelId:"team",sender:"Bram",text:"Wie neemt de promo voor vanavond nog op?",time:"08:05"},
 {id:"m5",channelId:"tibo",sender:"Tibo",text:"Heb je straks 5 minuten voor de Top 50?",time:"08:14"}];
const fallbackPeople=["Jasper","Tibo","Sarah","Bram","Wouter","Techniek","Marketing"];
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
function useStored<T>(key:string,initial:T){const[v,s]=useState<T>(initial);const[r,setR]=useState(false);useEffect(()=>{try{const x=localStorage.getItem(key);if(x)s(JSON.parse(x))}catch{}setR(true)},[key]);useEffect(()=>{if(r)try{localStorage.setItem(key,JSON.stringify(v))}catch{}},[key,r,v]);return[v,s]as const}

export default function MessengerModule({stationSlug}:{stationSlug:string}){
 const[channels,setChannels]=useStored<Channel[]>(`vlacora:${stationSlug}:messenger:channels:v4`,seedChannels);
 const[messages,setMessages]=useStored<Message[]>(`vlacora:${stationSlug}:messenger:messages:v4`,seedMessages);
 const[selectedId,setSelectedId]=useState(seedChannels[0].id);const[draft,setDraft]=useState("");const[search,setSearch]=useState("");const[showCreate,setShowCreate]=useState(false);
 const[newName,setNewName]=useState("");const[newType,setNewType]=useState<Channel["type"]>("group");const[newStation,setNewStation]=useState(stationSlug==="all"?"versuz":stationSlug);const[newMembers,setNewMembers]=useState<string[]>(["Tibo"]);const[people,setPeople]=useState<string[]>(fallbackPeople);const[notice,setNotice]=useState("");
 useEffect(()=>{if(!channels.some(c=>c.id===selectedId)&&channels[0])setSelectedId(channels[0].id)},[channels,selectedId]);useEffect(()=>{refreshPeople()},[newStation]);
 const selected=channels.find(c=>c.id===selectedId)||channels[0];const shownChannels=channels.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())&&(stationSlug==="all"||c.station===stationSlug||c.station==="all"));const selectedMessages=useMemo(()=>messages.filter(m=>m.channelId===selected?.id),[messages,selected?.id]);
 function flash(x:string){setNotice(x);setTimeout(()=>setNotice(""),2200)}
 function refreshPeople(){const pool=new Set(fallbackPeople);for(const slug of [newStation,"versuz","club-fm","vlacora-one","all"]){try{const raw=localStorage.getItem(`vlacora:${slug}:team`);if(raw){const arr:TeamMember[]=JSON.parse(raw);arr.forEach(p=>pool.add(p.name))}}catch{}}setPeople(Array.from(pool).sort())}
 function send(){if(!draft.trim()||!selected)return;setMessages([...messages,{id:uid(),channelId:selected.id,sender:"Jasper",text:draft.trim(),time:new Date().toLocaleTimeString("nl-BE",{hour:"2-digit",minute:"2-digit"})}]);setDraft("")}
 function create(){const members=newType==="direct"?["Jasper",newMembers[0]||"Tibo"]:Array.from(new Set(["Jasper",...newMembers]));const name=newType==="direct"?(newMembers[0]||"Privé"):newName.trim();if(!name)return flash("Kies een gebruiker of geef een naam.");const c={id:uid(),name,type:newType,members,unread:0,station:newStation};setChannels([...channels,c]);setSelectedId(c.id);setShowCreate(false);setNewName("");flash("Gesprek aangemaakt")}
 function toggleMember(name:string){setNewMembers(newMembers.includes(name)?newMembers.filter(x=>x!==name):[...newMembers,name])}
 return <div className="messenger messenger-v4"><div className="channels"><div className="module-title-row"><div><h3>Messenger</h3><small>Privé, groepen en stationchats</small></div><button className="primary tiny-btn" onClick={()=>setShowCreate(!showCreate)}>＋</button></div><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Zoek gesprek..."/>
 {showCreate&&<div className="channel-create-v4"><div className="two-form-cols"><label className="field">Type<select className="select" value={newType} onChange={e=>setNewType(e.target.value as Channel["type"])}><option value="group">Groep</option><option value="direct">Privé</option><option value="station">Stationkanaal</option></select></label><label className="field">Station<select className="select" value={newStation} onChange={e=>setNewStation(e.target.value)}>{stations.filter(s=>s.slug!=="all").map(s=><option value={s.slug} key={s.slug}>{s.name}</option>)}</select></label></div>{newType!=="direct"&&<label className="field">Naam gesprek<input className="input" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="bv. Muziekredactie"/></label>}<div className="member-picker-head"><strong>{newType==="direct"?"Kies gebruiker":"Leden"}</strong><button className="ghost small-action" onClick={refreshPeople}>↻ Refresh gebruikers</button></div><div className="member-picker">{people.filter(p=>p!=="Jasper").map(p=><label className={`member-chip ${newMembers.includes(p)?"selected":""}`} key={p}><input type={newType==="direct"?"radio":"checkbox"} checked={newMembers.includes(p)} onChange={()=>newType==="direct"?setNewMembers([p]):toggleMember(p)}/><span>{p}</span></label>)}</div><div className="button-row"><button className="primary" onClick={create}>Aanmaken</button><button className="ghost" onClick={()=>setShowCreate(false)}>Annuleren</button></div></div>}
 <div className="channel-list">{shownChannels.map(c=><button key={c.id} onClick={()=>{setSelectedId(c.id);setChannels(channels.map(x=>x.id===c.id?{...x,unread:0}:x))}} className={`channel ${selected?.id===c.id?"selected":""}`}><span className="channel-avatar">{c.type==="direct"?c.name.slice(0,1).toUpperCase():c.type==="station"?"◉":"✉"}</span><div><strong>{c.name}</strong><small>{stations.find(s=>s.slug===c.station)?.name||"Alle zenders"} • {c.type==="direct"?"privé":`${c.members.length} leden`}</small></div>{c.unread>0&&<span className="nav-count">{c.unread}</span>}</button>)}</div></div>
 <div className="chat">{selected?<><div className="chat-head"><div><strong>{selected.type==="direct"?selected.name:`#${selected.name}`}</strong><small>{selected.members.join(" • ")}</small></div><div className="button-row"><button className="ghost" onClick={()=>flash(`Leden: ${selected.members.join(", ")}`)}>Leden</button><button className="ghost" onClick={()=>{setChannels(channels.filter(c=>c.id!==selected.id));setMessages(messages.filter(m=>m.channelId!==selected.id));flash("Gesprek verwijderd")}}>Verwijder</button></div></div>{notice&&<div className="inline-notice">{notice}</div>}<div className="messages">{selectedMessages.length===0&&<div className="empty-chat"><strong>Nog geen berichten</strong><span>Stuur het eerste bericht.</span></div>}{selectedMessages.map(m=><div className={`message ${m.sender==="Jasper"?"mine":""}`} key={m.id}><div className="avatar small">{m.sender.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><div className="message-meta"><strong>{m.sender}</strong><span>{m.time}</span></div><p>{m.text}</p></div></div>)}</div><div className="composer"><button className="ghost" onClick={()=>flash("Bestandsupload volgt met Supabase Storage.")}>＋</button><input className="input grow" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={`Bericht naar ${selected.name}...`}/><button className="primary" onClick={send}>Verstuur</button></div></>:<div className="empty-chat"><strong>Geen gesprek geselecteerd</strong></div>}</div></div>
}
