"use client";
import { useEffect,useMemo,useState } from "react";
import jsPDF from "jspdf";
import type { MusicSong } from "@/components/modules/music-library-module";
import { pathFor,pathForFolder,radioRead,readIntegration,readMappings } from "@/lib/radio/client-config";
import { useHubStation } from "@/lib/radio/hub-stations";

type LiveFolder={id:string;name:string;description?:string;count?:number};
type LiveSong={id:string;artist:string;title:string;category?:string;year?:string};
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
function useStored<T>(key:string,initial:T){const[v,setV]=useState<T>(initial);const[r,setR]=useState(false);useEffect(()=>{try{const x=localStorage.getItem(key);if(x)setV(JSON.parse(x))}catch{}setR(true)},[key]);useEffect(()=>{if(r)try{localStorage.setItem(key,JSON.stringify(v))}catch{}},[key,r,v]);return[v,setV] as const}

export default function MusicFoldersModule({stationSlug}:{stationSlug:string}){
  const station=useHubStation(stationSlug);const mapping=readMappings()[stationSlug];const rotationId=mapping?.rotationId||station.rotationId||"";
  const[mode,setMode]=useState<"rotation"|"local">("rotation");const[liveFolders,setLiveFolders]=useState<LiveFolder[]>([]);const[liveSongs,setLiveSongs]=useState<LiveSong[]>([]);const[selectedFolder,setSelectedFolder]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  const[localSongs,setLocalSongs]=useStored<MusicSong[]>(`vlacora:${stationSlug}:music:catalog`,[]);const[selectedLocalMap,setSelectedLocalMap]=useState("");const[docs,setDocs]=useStored<{id:string;name:string;created:string}[]>(`vlacora:${stationSlug}:musicfolders:docs`,[]);
  const localMaps=useMemo(()=>Array.from(new Set(localSongs.map(s=>s.rotationMap).filter(Boolean))).sort(),[localSongs]);
  const localMapSongs=localSongs.filter(s=>!selectedLocalMap||s.rotationMap===selectedLocalMap);
  function flash(x:string){setNotice(x);setTimeout(()=>setNotice(""),3200)}
  function refreshLocal(){try{const raw=localStorage.getItem(`vlacora:${stationSlug}:music:catalog`);setLocalSongs(raw?JSON.parse(raw):[])}catch{setLocalSongs([])}}
  async function loadFolders(){const cfg=readIntegration("rotation");if(!cfg?.host)return flash("Rotation One is nog niet ingesteld.");if(!rotationId)return flash("Dit Hub-station heeft nog geen Rotation One station-ID.");if(!cfg.musicFoldersPath)return flash("Vul eerst in Beheer het bevestigde Rotation One muziekmappen-endpoint in. VLACORA gokt dit endpoint bewust niet.");setBusy(true);try{const path=pathFor(cfg.musicFoldersPath,rotationId);const data=await radioRead("rotation",path,"folders");const folders=data.folders||[];setLiveFolders(folders);if(folders[0]){setSelectedFolder(folders[0].id);await loadSongs(folders[0].id)}flash(`${folders.length} Rotation One-mappen opgehaald`)}catch(e){flash(e instanceof Error?e.message:"Mappen ophalen mislukt")}finally{setBusy(false)}}
  async function loadSongs(folderId:string){const cfg=readIntegration("rotation");if(!cfg?.musicFolderItemsPath)return flash("Songs-in-map endpoint is nog niet ingesteld.");if(!rotationId)return;setBusy(true);try{const data=await radioRead("rotation",pathForFolder(cfg.musicFolderItemsPath,rotationId,folderId),"songs");setLiveSongs(data.songs||[]);flash(`${(data.songs||[]).length} songs geladen`)}catch(e){setLiveSongs([]);flash(e instanceof Error?e.message:"Songs ophalen mislukt")}finally{setBusy(false)}}
  function generatePdf(){const currentFolder=mode==="rotation"?liveFolders.find(f=>f.id===selectedFolder):null;const rows=mode==="rotation"?liveSongs.map(s=>({artist:s.artist,title:s.title,map:currentFolder?.name||"Rotation One"})):localMapSongs.map(s=>({artist:s.artist,title:s.title,map:s.rotationMap||"VLACORA"}));if(!rows.length)return flash("Geen songs om in de PDF te zetten.");const doc=new jsPDF({unit:"mm",format:"a4"});const W=210,margin=16;let page=1,y=42;const bg=()=>{doc.setFillColor(31,31,117);doc.rect(0,0,210,297,"F");doc.setFillColor(77,55,210);doc.circle(184,28,48,"F");doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");doc.setFontSize(22);doc.text("VLACORA",margin,19);doc.setFontSize(8);doc.setFont("helvetica","normal");doc.text("INTERNAL MUSIC COMMUNICATION",margin,25);doc.text(`Pagina ${page}`,W-margin,287,{align:"right"})};bg();doc.setFont("helvetica","bold");doc.setFontSize(22);doc.text("MUZIEKMAP / PLAYLIST",margin,y);y+=8;doc.setFontSize(11);doc.text(mode==="rotation"?(currentFolder?.name||"Rotation One map"):(selectedLocalMap||"Alle lokale songs"),margin,y);y+=7;doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(210,215,255);doc.text(`${station.name} • ${rows.length} songs • ${new Date().toLocaleString("nl-BE")}`,margin,y);y+=11;rows.forEach((r,i)=>{if(y>270){doc.addPage();page++;bg();y=40}if(i%2===0){doc.setFillColor(47,47,137);doc.roundedRect(margin,y-4,W-margin*2,8,1,1,"F")}doc.setTextColor(255,255,255);doc.setFontSize(9);doc.setFont("helvetica","bold");doc.text(String(i+1).padStart(2,"0"),margin+2,y);doc.text(r.artist||"—",margin+14,y);doc.setFont("helvetica","normal");doc.text(r.title||"—",88,y);doc.setTextColor(190,195,255);doc.text(r.map,W-margin-3,y,{align:"right"});y+=9});const filename=`vlacora-${station.name}-${mode==="rotation"?(currentFolder?.name||"rotation"):selectedLocalMap||"muziek"}-${new Date().toISOString().slice(0,10)}.pdf`.toLowerCase().replace(/[^a-z0-9.-]+/g,"-");doc.save(filename);setDocs([{id:uid(),name:filename,created:new Date().toLocaleString("nl-BE")},...docs]);flash("PDF gemaakt")}
  const cfg=typeof window!=="undefined"?readIntegration("rotation"):null;
  return <div>
    <div className="page-intro"><div><h2>Muziekmap → PDF</h2><p>Kies een echte Rotation One-map uit een menu en haal de songs uit die map op voor de interne PDF.</p></div><button className="primary" onClick={generatePdf}>PDF maken</button></div>
    {notice&&<div className="inline-notice standalone">{notice}</div>}
    <div className="source-tabs"><button className={mode==="rotation"?"active":""} onClick={()=>setMode("rotation")}>Rotation One live</button><button className={mode==="local"?"active":""} onClick={()=>setMode("local")}>VLACORA bibliotheek</button></div>
    {mode==="rotation"?<div className="two-col">
      <div className="card"><div className="module-title-row"><div><h3>Rotation One muziekmap</h3><small>{station.name} • station ID {rotationId||"niet gekoppeld"}</small></div><button className="ghost" disabled={busy} onClick={loadFolders}>↻ Mappen ophalen</button></div>
        {!cfg?.musicFoldersPath&&<div className="http-warning"><strong>Endpoint nog nodig</strong><span>De publieke API voor stations/schedules is bevestigd, maar het database-folderendpoint nog niet. Vul in Beheer alleen het echte endpoint in zodra dat in Rotation One beschikbaar is; VLACORA verzint er geen.</span></div>}
        <label className="field">Map<select className="select" value={selectedFolder} onChange={e=>{setSelectedFolder(e.target.value);loadSongs(e.target.value)}}><option value="">Kies een Rotation One-map…</option>{liveFolders.map(f=><option value={f.id} key={f.id}>{f.name}{f.count!=null?` • ${f.count} songs`:""}</option>)}</select></label>
        <div className="music-folder-api-meta"><span>Mappen endpoint</span><strong>{cfg?.musicFoldersPath||"niet ingesteld"}</strong><span>Songs endpoint</span><strong>{cfg?.musicFolderItemsPath||"niet ingesteld"}</strong></div>
      </div>
      <div className="card"><div className="module-title-row"><div><h3>Songs in gekozen map</h3><small>{liveSongs.length} items uit Rotation One</small></div></div>{liveSongs.length===0?<div className="empty-live-state"><strong>Nog geen songs geladen</strong><span>Kies een map om de echte inhoud op te halen.</span></div>:<div className="live-folder-song-list">{liveSongs.map((s,i)=><div className="live-folder-song" key={`${s.id}-${i}`}><span>{i+1}</span><div><strong>{s.artist||"—"}</strong><small>{s.title}</small></div><b>{s.category||""}</b></div>)}</div>}</div>
    </div>:<div className="two-col"><div className="card"><div className="module-title-row"><div><h3>VLACORA bibliotheek</h3><small>{localSongs.length} lokale songs</small></div><button className="ghost" onClick={refreshLocal}>↻ Refresh</button></div><label className="field">Rotation map<select className="select" value={selectedLocalMap} onChange={e=>setSelectedLocalMap(e.target.value)}><option value="">Alle maps</option>{localMaps.map(m=><option key={m}>{m}</option>)}</select></label></div><div className="card"><h3>PDF selectie</h3><p><strong>{localMapSongs.length}</strong> songs worden opgenomen.</p>{localMapSongs.slice(0,12).map((s,i)=><div className="document-row" key={s.id}><span>{i+1}</span><div><strong>{s.artist}</strong><small>{s.title} • {s.rotationMap}</small></div></div>)}</div></div>}
    <div className="card"><h3>Gemaakte documenten</h3>{docs.length===0?<p className="muted">Nog geen PDF gemaakt.</p>:docs.slice(0,8).map(d=><div className="document-row" key={d.id}><div><strong>{d.name}</strong><small>{d.created}</small></div><button className="mini-btn danger" onClick={()=>setDocs(docs.filter(x=>x.id!==d.id))}>×</button></div>)}</div>
  </div>
}
