"use client";
import { useEffect,useMemo,useState } from "react";
import AttachmentPanel from "@/components/attachment-panel";
import { loadSharedProgramming } from "@/lib/supabase/hub-data";
import { loadMusicProposals,submitMusicProposal,updateMusicProposal,type MusicProposal } from "@/lib/supabase/music-proposals";
import { useCollaboration } from "@/components/collaboration/collaboration-provider";

const labels={new_song:"Nieuwe song",format_change:"Formatwijziging",playlist_suggestion:"Playlist-/inhoudsuggestie"} as const;
const statusLabels={submitted:"Ingediend",reviewing:"In review",approved:"Goedgekeurd",rejected:"Afgewezen",implemented:"Uitgevoerd"} as const;
export default function MusicProposalsModule({stationSlug}:{stationSlug:string}){
 const collab=useCollaboration();const[rows,setRows]=useState<MusicProposal[]>([]);const[selectedId,setSelectedId]=useState("");const[showCreate,setShowCreate]=useState(false);const[type,setType]=useState<MusicProposal["proposalType"]>("new_song");const[programs,setPrograms]=useState<any[]>([]);const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
 async function load(){try{const r=await loadMusicProposals(stationSlug);setRows(r);setSelectedId(x=>x&&r.some(y=>y.id===x)?x:r[0]?.id||"")}catch(e){setNotice(e instanceof Error?e.message:"Voorstellen laden mislukt")}}
 useEffect(()=>{void load();if(stationSlug!=="all")void loadSharedProgramming(stationSlug).then(setPrograms).catch(()=>{})},[stationSlug]);
 const selected=rows.find(x=>x.id===selectedId)||null;const grouped=useMemo(()=>({open:rows.filter(x=>!['rejected','implemented'].includes(x.status)),done:rows.filter(x=>['rejected','implemented'].includes(x.status))}),[rows]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(stationSlug==="all")return setNotice("Kies eerst één zender.");const f=new FormData(e.currentTarget);setBusy(true);try{const p=await submitMusicProposal({stationSlug,proposalType:type,title:String(f.get("title")||"").trim(),artist:String(f.get("artist")||"").trim(),songTitle:String(f.get("songTitle")||"").trim(),targetFolder:String(f.get("targetFolder")||"").trim(),targetProgramId:String(f.get("targetProgramId")||"")||null,spotifyUrl:String(f.get("spotifyUrl")||"").trim(),youtubeUrl:String(f.get("youtubeUrl")||"").trim(),currentValue:String(f.get("currentValue")||"").trim(),proposedValue:String(f.get("proposedValue")||"").trim(),explanation:String(f.get("explanation")||"").trim()});setShowCreate(false);await load();setSelectedId(p.id);setNotice("Voorstel ingediend. Bestanden kan je rechts toevoegen.")}catch(e){setNotice(e instanceof Error?e.message:"Indienen mislukt")}finally{setBusy(false)}}
 async function setStatus(status:MusicProposal["status"]){if(!selected)return;try{await updateMusicProposal(selected.id,{status});await load();setNotice(`Status: ${statusLabels[status]}`)}catch(e){setNotice(e instanceof Error?e.message:"Status aanpassen mislukt")}}
 return <div><div className="page-intro"><div><span className="eyebrow">MUZIEK & FORMAT</span><h2>Voorstellen</h2><p>Iedereen met zendertoegang kan meteen een song, playlist-/inhoudswijziging of formatwijziging voorstellen.</p></div><button className="primary" disabled={stationSlug==="all"} onClick={()=>setShowCreate(true)}>+ Nieuw voorstel</button></div>{notice&&<div className="inline-notice standalone">{notice}</div>}
 <div className="proposal-stats"><div className="card"><strong>{grouped.open.length}</strong><span>open</span></div><div className="card"><strong>{rows.filter(x=>x.proposalType==='new_song').length}</strong><span>songvoorstellen</span></div><div className="card"><strong>{rows.filter(x=>x.proposalType==='format_change').length}</strong><span>formatwijzigingen</span></div></div>
 <div className="proposal-layout"><div className="card proposal-list"><div className="module-title-row"><div><h3>Voorstellen</h3><small>{rows.length} totaal</small></div><button className="ghost" onClick={()=>void load()}>↻</button></div>{rows.map(x=><button key={x.id} className={`proposal-row ${selectedId===x.id?"selected":""}`} onClick={()=>setSelectedId(x.id)}><span className={`proposal-type ${x.proposalType}`}>{labels[x.proposalType]}</span><div><strong>{x.title}</strong><small>{x.submitterName} • {new Date(x.createdAt).toLocaleDateString("nl-BE")}</small></div><span className="badge badge-blue">{statusLabels[x.status]}</span></button>)}{!rows.length&&<div className="empty-live-state compact"><strong>Nog geen voorstellen</strong><span>Een teamlid kan hier zelf een voorstel indienen.</span></div>}</div>
 {selected?<div className="proposal-detail-column"><div className="card"><div className="section-head"><div><span className="eyebrow">{labels[selected.proposalType]}</span><h2>{selected.title}</h2><p>Ingediend door {selected.submitterName}</p></div><span className="badge badge-blue">{statusLabels[selected.status]}</span></div>{selected.proposalType==='new_song'&&<div className="proposal-song-card"><strong>{selected.artist} — {selected.songTitle}</strong><span>Voorgestelde map: {selected.targetFolder||"nog niet gekozen"}</span><div className="button-row">{selected.spotifyUrl&&<a className="ghost" href={selected.spotifyUrl} target="_blank" rel="noreferrer">Spotify ↗</a>}{selected.youtubeUrl&&<a className="ghost" href={selected.youtubeUrl} target="_blank" rel="noreferrer">YouTube ↗</a>}</div></div>}{selected.proposalType!=='new_song'&&<div className="two-form-cols"><div><small>Huidig</small><p>{selected.currentValue||"—"}</p></div><div><small>Voorstel</small><p>{selected.proposedValue||"—"}</p></div></div>}<label className="field">Uitleg<textarea className="input textarea" value={selected.explanation} readOnly/></label>{selected.targetProgramId&&<p className="muted">Programma: {programs.find(p=>p.id===selected.targetProgramId)?.name||selected.targetProgramId}</p>}<div className="proposal-status-actions"><button className="ghost" onClick={()=>void setStatus("reviewing")}>In review</button><button className="ghost positive-action" onClick={()=>void setStatus("approved")}>Goedkeuren</button><button className="ghost" onClick={()=>void setStatus("implemented")}>Als uitgevoerd</button><button className="ghost danger-text" onClick={()=>void setStatus("rejected")}>Afwijzen</button></div></div><div className="card"><AttachmentPanel stationSlug={selected.stationSlug} entityType="music_proposal" entityId={selected.id} title="Bijlagen bij voorstel"/></div></div>:<div className="card empty-live-state"><strong>Kies een voorstel</strong><span>Details en bestanden verschijnen hier.</span></div>}</div>
 {showCreate&&<div className="modal-backdrop" onMouseDown={()=>setShowCreate(false)}><div className="modal-card proposal-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>Nieuw muziek-/formatvoorstel</h2><button className="mini-btn" onClick={()=>setShowCreate(false)}>×</button></div><form className="modal-form" onSubmit={create}><label className="field">Soort<select className="select" value={type} onChange={e=>setType(e.target.value as any)}><option value="new_song">Nieuwe song voor muziekmap</option><option value="format_change">Aanpassing aan format</option><option value="playlist_suggestion">Playlist-/inhoudsuggestie</option></select></label><label className="field">Korte titel<input className="input" name="title" required placeholder="bv. Meer 2000s in Drive"/></label>{type==='new_song'?<><div className="two-form-cols"><label className="field">Artiest<input className="input" name="artist" required/></label><label className="field">Titel<input className="input" name="songTitle" required/></label></div><label className="field">Voor welke map?<input className="input" name="targetFolder" placeholder="A-map, B-map, recurrent, gold…"/></label><div className="two-form-cols"><label className="field">Spotify-link<input className="input" name="spotifyUrl" type="url" placeholder="https://open.spotify.com/…"/></label><label className="field">YouTube-link<input className="input" name="youtubeUrl" type="url" placeholder="https://youtube.com/…"/></label></div></>:<><label className="field">Programma (optioneel)<select className="select" name="targetProgramId"><option value="">Hele zender / geen specifiek programma</option>{programs.map(p=><option value={p.id} key={p.id}>{p.name} • {p.start}</option>)}</select></label><div className="two-form-cols"><label className="field">Hoe is het nu?<textarea className="input textarea small" name="currentValue"/></label><label className="field">Wat stel je voor?<textarea className="input textarea small" name="proposedValue"/></label></div></>}<label className="field">Waarom / extra uitleg<textarea className="input textarea" name="explanation" required placeholder="Leg kort uit waarom dit beter past bij het format of de doelgroep…"/></label><button className="primary" disabled={busy}>{busy?"Indienen…":"Voorstel indienen"}</button><small>Na opslaan kun je onmiddellijk bestanden toevoegen.</small></form></div></div>}</div>
}
