"use client";
import { useEffect, useState } from "react";

type Template={id:string;name:string;label:string;layout:string;caption:string;background:string};
type Draft={id:string;templateId:string;artist:string;title:string;caption:string;status:string};
const seeds:Template[]=[
 {id:"st1",name:"Tune of the Week",label:"TUNE OF THE WEEK",layout:"Music hero",caption:"🔥 Deze week onze Tune of the Week: {artist} - {title}. Nu op {station}.",background:"purple"},
 {id:"st2",name:"Nieuwe #1",label:"NEW NUMBER ONE",layout:"Chart",caption:"🏆 Een nieuwe nummer 1! {artist} - {title} staat bovenaan onze lijst.",background:"dark"},
 {id:"st3",name:"Grootste stijger",label:"BIGGEST CLIMBER",layout:"Chart",caption:"📈 De grootste stijger van deze week: {artist} - {title}.",background:"pink"},
 {id:"st4",name:"Now On Air",label:"NOW ON AIR",layout:"Program",caption:"🔴 Nu live: {title} met {artist}. Luister mee op {station}.",background:"green"},
];
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function useStored<T>(key:string,initial:T){const[v,s]=useState(initial);const[r,setR]=useState(false);useEffect(()=>{try{const x=localStorage.getItem(key);if(x)s(JSON.parse(x))}catch{}setR(true)},[key]);useEffect(()=>{if(r)try{localStorage.setItem(key,JSON.stringify(v))}catch{}},[key,r,v]);return[v,s]as const}
export default function SocialStudioModule({stationSlug}:{stationSlug:string}){
 const[templates,setTemplates]=useStored<Template[]>(`vlacora:${stationSlug}:social:templates`,seeds);const[drafts,setDrafts]=useStored<Draft[]>(`vlacora:${stationSlug}:social:drafts`,[]);const[selectedId,setSelectedId]=useState(seeds[0].id);const[artist,setArtist]=useState("Joel Corry");const[title,setTitle]=useState("Whisper");const[showNew,setShowNew]=useState(false);
 const t=templates.find(x=>x.id===selectedId)||templates[0];
 function update(p:Partial<Template>){if(!t)return;setTemplates(templates.map(x=>x.id===t.id?{...x,...p}:x))}
 function create(){const name=prompt("Naam van het nieuwe social template:");if(!name)return;const n={id:uid(),name,label:name.toUpperCase(),layout:"Custom",caption:"{artist} - {title} op {station}",background:"blue"};setTemplates([...templates,n]);setSelectedId(n.id);setShowNew(false)}
 const caption=(t?.caption||"").replaceAll("{artist}",artist).replaceAll("{title}",title).replaceAll("{station}",stationSlug==="all"?"VLACORA":stationSlug);
 function saveDraft(){if(!t)return;setDrafts([{id:uid(),templateId:t.id,artist,title,caption,status:"Concept"},...drafts]);alert("Social post als concept opgeslagen.")}
 function download(){const c=document.createElement("canvas");c.width=1080;c.height=1350;const x=c.getContext("2d");if(!x)return;const color=t.background==="pink"?"#b83280":t.background==="green"?"#137b67":t.background==="dark"?"#16162d":t.background==="blue"?"#2255aa":"#29279c";const g=x.createLinearGradient(0,0,1080,1350);g.addColorStop(0,color);g.addColorStop(1,"#6848ff");x.fillStyle=g;x.fillRect(0,0,1080,1350);x.fillStyle="rgba(255,255,255,.08)";x.beginPath();x.arc(850,230,330,0,Math.PI*2);x.fill();x.fillStyle="#fff";x.font="bold 58px Arial";x.fillText("VLACORA",70,100);x.font="bold 42px Arial";x.fillText(t.label,70,270);x.font="bold 76px Arial";wrapText(x,artist,70,770,920,86);x.font="52px Arial";wrapText(x,title,70,940,920,65);x.font="bold 28px Arial";x.fillText("RADIO • TEAM • CONTENT",70,1250);const a=document.createElement("a");a.href=c.toDataURL("image/png");a.download=`vlacora-${t.name}.png`.replace(/\s+/g,"-").toLowerCase();a.click()}
 function wrapText(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,max:number,line:number){const words=text.split(" ");let l="";for(const w of words){const test=l+w+" ";if(ctx.measureText(test).width>max&&l){ctx.fillText(l,x,y);l=w+" ";y+=line}else l=test}ctx.fillText(l,x,y)}
 return <div><div className="page-intro"><div><h2>Social Studio</h2><p>Maak, bewerk en bewaar je eigen posttemplates per zender.</p></div><button className="primary" onClick={create}>+ Nieuw template</button></div><div className="social-v3-layout"><div className="card social-template-list"><h3>Templates</h3>{templates.map(x=><button className={`social-template-option ${x.id===t?.id?"selected":""}`} onClick={()=>setSelectedId(x.id)} key={x.id}><strong>{x.name}</strong><span>{x.layout}</span></button>)}<hr/><h3>Conceptposts</h3>{drafts.slice(0,4).map(d=><div className="draft-row" key={d.id}><div><strong>{d.artist} - {d.title}</strong><small>{d.status}</small></div><button className="mini-btn danger" onClick={()=>setDrafts(drafts.filter(x=>x.id!==d.id))}>×</button></div>)}</div>
 {t&&<div className="card social-template-editor"><div className="section-head"><div><span className="eyebrow">TEMPLATE EDITOR</span><h2>{t.name}</h2></div><button className="ghost" onClick={()=>{if(confirm("Template verwijderen?")){setTemplates(templates.filter(x=>x.id!==t.id));setSelectedId(templates.find(x=>x.id!==t.id)?.id||"")}}}>Verwijder</button></div><div className="two-form-cols"><label className="field">Templatenaam<input className="input" value={t.name} onChange={e=>update({name:e.target.value})}/></label><label className="field">Visual label<input className="input" value={t.label} onChange={e=>update({label:e.target.value})}/></label><label className="field">Layout<select className="select" value={t.layout} onChange={e=>update({layout:e.target.value})}><option>Music hero</option><option>Chart</option><option>Program</option><option>Event</option><option>Custom</option></select></label><label className="field">Achtergrond<select className="select" value={t.background} onChange={e=>update({background:e.target.value})}><option value="purple">Paars</option><option value="blue">Blauw</option><option value="pink">Roze</option><option value="green">Groen</option><option value="dark">Donker</option></select></label></div><label className="field">Caption-sjabloon<textarea className="input textarea" value={t.caption} onChange={e=>update({caption:e.target.value})}/><span className="helper">Variabelen: {"{artist} {title} {station}"}</span></label><div className="two-form-cols"><label className="field">Artiest<input className="input" value={artist} onChange={e=>setArtist(e.target.value)}/></label><label className="field">Titel / programma<input className="input" value={title} onChange={e=>setTitle(e.target.value)}/></label></div><div className="caption-preview"><strong>Caption preview</strong><p>{caption}</p></div><div className="button-row"><button className="ghost" onClick={download}>Download PNG</button><button className="primary" onClick={saveDraft}>Als concept bewaren</button></div></div>}
 <div className={`social-preview social-preview-${t?.background||"purple"}`}><div className="social-brand">VLACORA<span>radio</span></div><div className="social-label">{t?.label}</div><div className="social-art">♫</div><h2>{artist}</h2><h3>{title}</h3><div className="social-bottom">RADIO • TEAM • CONTENT</div></div></div></div>
}
