export const navItems = [
  ["dashboard", "⌂", "TODAY"],
  ["voor-mij", "◎", "Voor mij"],
  ["mijn-uitzending", "◉", "Mijn uitzending"],
  ["meldingen", "🔔", "Meldingen"],
  ["stations", "◉", "Stations"],
  ["taken", "✓", "Taken"],
  ["meldpunt", "!", "Meldpunt"],
  ["aanvragen", "＋", "Aanvragen"],
  ["content-inbox", "▤", "Content-inbox"],
  ["messenger", "✉", "Messenger"],
  ["communicatie", "▣", "Communicatie"],
  ["kalender", "□", "Kalender"],
  ["programmering", "◫", "Programmering"],
  ["programmas", "▣", "Programma-pagina's"],
  ["afwezigheden", "↔", "Afwezigheden"],
  ["contacten", "☎", "Contacten"],
  ["sjablonen", "▧", "Sjablonen"],
  ["muziek", "♫", "Muziek"],
  ["muziek-voorstellen", "＋", "Muziek & formatvoorstellen"],
  ["meetings", "◎", "Muziekmeetings"],
  ["redactie", "✎", "Redactie"],
  ["verkeer", "⌁", "Verkeer"],
  ["hitlijsten", "↕", "Hitlijsten"],
  ["presentatie", "✎", "Presentatie"],
  ["social", "✦", "Social Studio"],
  ["team", "♙", "Team"],
  ["beheer", "⚙", "Beheer"]
] as const;
