export const navItems = [
  ["dashboard", "⌂", "TODAY"],
  ["voor-mij", "◎", "Voor mij"],
  ["mijn-uitzending", "◉", "Mijn uitzending"],
  ["meldingen", "🔔", "Meldingen"],
  ["stations", "◉", "Stations"],
  ["taken", "✓", "Taken"],
  ["meldpunt", "!", "Meldpunt"],
  ["aanvragen", "＋", "Aanvragen"],
  ["content-inbox", "▤", "Content-inbox"],
  ["messenger", "✉", "Messenger"],
  ["communicatie", "▣", "Communicatie"],
  ["kalender", "□", "Kalender"],
  ["programmering", "◫", "Programmering"],
  ["beschikbaarheid", "◷", "Beschikbaarheid"],
  ["programmas", "▣", "Programma-pagina's"],
  ["afwezigheden", "↔", "Afwezigheden"],
  ["contacten", "☎", "Contacten"],
  ["sjablonen", "⌘", "Workflowbouwer"],
  ["muziek", "♫", "Muziek"],
  ["muziek-voorstellen", "＋", "Muziek & formatvoorstellen"],
  ["meetings", "◎", "Muziekmeetings"],
  ["redactie", "✎", "Redactie"],
  ["verkeer", "⌁", "Verkeer"],
  ["hitlijsten", "↕", "Hitlijsten"],
  ["presentatie", "✎", "Presentatie"],
  ["social", "✦", "Social Studio"],
  ["team", "♙", "Team"],
  ["meldpunt-beheer", "!", "Meldpuntbeheer"],
  ["beheer", "⚙", "Beheer"],
  ["hitlijst-beheer", "↕", "Hitlijstbeheer"],
  ["social-beheer", "✦", "Social beheer"],
  ["social-templatebouwer", "▦", "Social templatebouwer"]
] as const;

export const adminNavSlugs = ["beheer","stations","team","meldpunt-beheer","sjablonen","hitlijst-beheer","social-beheer","social-templatebouwer"] as const;
