-- PULSE 0.28.0
-- Database tables for Lezers & Polls. The active Supabase project already contains this schema.
create table if not exists public.hub_announcement_recipients (announcement_id uuid not null references public.hub_announcements(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,delivered_at timestamptz not null default now(),first_read_at timestamptz,last_read_at timestamptz,acknowledged_at timestamptz,primary key(announcement_id,user_id));
create table if not exists public.hub_announcement_polls (id uuid primary key default gen_random_uuid(),announcement_id uuid not null references public.hub_announcements(id) on delete cascade,question text not null,allow_multiple boolean not null default false,required boolean not null default false,sort_order integer not null default 100,created_at timestamptz not null default now());
create table if not exists public.hub_announcement_poll_options (id uuid primary key default gen_random_uuid(),poll_id uuid not null references public.hub_announcement_polls(id) on delete cascade,label text not null,sort_order integer not null default 100,created_at timestamptz not null default now());
create table if not exists public.hub_announcement_poll_votes (poll_id uuid not null references public.hub_announcement_polls(id) on delete cascade,option_id uuid not null references public.hub_announcement_poll_options(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(poll_id,option_id,user_id));
create table if not exists public.hub_announcement_replies (id uuid primary key default gen_random_uuid(),announcement_id uuid not null references public.hub_announcements(id) on delete cascade,recipient_user_id uuid not null references public.profiles(id) on delete cascade,sender_user_id uuid not null references public.profiles(id) on delete cascade,body text not null,created_at timestamptz not null default now());
alter table public.hub_announcement_recipients enable row level security;alter table public.hub_announcement_polls enable row level security;alter table public.hub_announcement_poll_options enable row level security;alter table public.hub_announcement_poll_votes enable row level security;alter table public.hub_announcement_replies enable row level security;
-- Policies are intentionally kept in the separate 046b file so upgrades can be audited independently.
